parameters:
#    city_quest.example.class: AthenaPlus\CityQuestBundle\Example

services:
#    city_quest.example:
#        class: %city_quest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
